# Data impoting and spliting

In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import fetch_20newsgroups

In [2]:
strain=['comp.graphics','rec.autos','rec.motorcycles', 'rec.sport.hockey', 'sci.space','soc.religion.christian']
stest=['comp.graphics','rec.autos','rec.motorcycles', 'rec.sport.hockey', 'sci.space','soc.religion.christian']

In [3]:

train=fetch_20newsgroups(subset='train',categories=strain)
test=fetch_20newsgroups(subset='test',categories=stest)

In [4]:
xtrain,xtest,ytrain,ytest=np.array(train.data),np.array(test.data),np.array(train.target),np.array(test.target)

In [5]:
print(xtrain.shape,ytrain.shape,xtest.shape,ytest.shape)

(3568,) (3568,) (2374,) (2374,)


In [6]:
d=pd.DataFrame(xtrain,columns=['News'])

In [7]:
d.shape

(3568, 1)

In [8]:
d1=pd.DataFrame(ytrain,columns=['target'])

In [9]:
d1.shape

(3568, 1)

In [10]:
df=pd.concat([d,d1],axis=1)

In [11]:
df.head(20)

News  target
0   From: scs8@cunixb.cc.columbia.edu (Sebastian C...       2
1   From: dannyb@panix.com (Daniel Burstein)\nSubj...       4
2   Subject: Re: Smiths birthday goal was LEAFS GO...       3
3   From: nsmca@aurora.alaska.edu\nSubject: Re: Wh...       4
4   From: sjp@hpuerca.atl.hp.com (Steve Phillips)\...       1
5   From: robert@cpuserver.acsc.com (Robert Grant)...       0
6   From: moseley@u.washington.edu (Steve L. Mosel...       2
7   From: tbrent@florin.ecn.purdue.edu (Timothy J ...       5
8   From: keith@hydra.unm.edu ()\nSubject: Where c...       2
9   Subject: Re: JETS FANS!  Hrivnak or Tabaracci?...       3
10  From: rgc3679@bcstec.ca.boeing.com (Robert G. ...       0
11  From: leech@cs.unc.edu (Jon Leech)\nSubject: S...       4
12  From: dgempey@ucscb.UCSC.EDU (David Gordon Emp...       4
13  From: wbdst+@pitt.edu (William B Dwinnell)\nSu...       0
14  From: Kurt Godden <godden@gmr.com>\nSubject: G...       1
15  From: bradw@Newbridge.COM (Brad Warkentin)\nSu...       2
16  From: gdoherty@us.oracle.com (Greg Doherty)\nS...       2
17  From: (Eric Youngblood)\nSubject: Re: Old Corv...       1
18  From: lmann@jjmhome.UUCP (Laurie Mann)\nSubjec...       1
19  From: kuryakin@bcstec.ca.boeing.com (Rick Pave...       0

In [12]:
#df['target']=[train.target_names[i] for i in df.target]

# cleaning data

In [13]:
import re

In [14]:
def clean(x):
    s=re.sub('<.*?>',' ',x)
    s=re.sub('[^A-Za-z]',' ',s)
    s=re.sub('\s+',' ',s)
    s=s.strip()
    return s.lower()

In [15]:
df['News']=df.News.apply(clean)

In [16]:
df.head()

News  target
0  from scs cunixb cc columbia edu sebastian c se...       2
1  from dannyb panix com daniel burstein subject ...       4
2  subject re smiths birthday goal was leafs go a...       3
3  from nsmca aurora alaska edu subject re why no...       4
4  from sjp hpuerca atl hp com steve phillips sub...       1

In [17]:
from nltk.corpus import stopwords

In [18]:
stop=stopwords.words('english')

In [19]:
print(stop)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [20]:
X=df.News.values
Y=df.target.values

In [21]:
X.shape

(3568,)

In [22]:
Y.shape

(3568,)

# countvectorizer

In [23]:
from sklearn.feature_extraction.text import CountVectorizer

In [24]:
cvt=CountVectorizer(stop_words=stop)

In [25]:
cv_train=cvt.fit_transform(X)

In [26]:
cv_train.shape

(3568, 37562)

In [27]:
cv_test=cvt.transform(xtest)

# Logistic Regression

In [28]:
from sklearn.linear_model import LogisticRegression

In [29]:
log=LogisticRegression()

In [30]:
log.fit(cv_train,Y)

LogisticRegression()

In [31]:
pred=log.predict(cv_train)

In [32]:
pred.shape

(3568,)

In [33]:
from sklearn.metrics import accuracy_score

In [34]:
train_scores=accuracy_score(Y,pred)
train_scores

0.9997197309417041

In [35]:
pred1=log.predict(cv_test)

In [36]:
test_scores=accuracy_score(ytest,pred1)
test_scores

0.9486099410278012

In [37]:
train.target_names

['comp.graphics',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.hockey',
 'sci.space',
 'soc.religion.christian']

# some external testing news samples

In [38]:
test=['The Indian hockey teams are unlikely to participate in next years Commonwealth Games in Birmingham to ensure that they hit peak form during the Asian Games, which is a qualifier for the 2024 Paris Olympics, IOA chief Narinder Batra said on Friday']

In [39]:
cleaned_data=[]

for i in test:           #Hockey news https://sports.ndtv.com/hockey/indian-hockey-teams-unlikely-to-compete-in-birmingham-cwg-ioa-chief-2528498
    t = clean(i)     
    cleaned_data.append(t)

In [40]:
cleaned_data

['the indian hockey teams are unlikely to participate in next years commonwealth games in birmingham to ensure that they hit peak form during the asian games which is a qualifier for the paris olympics ioa chief narinder batra said on friday']

In [41]:
t1=cvt.transform(cleaned_data)

In [42]:
log.predict(t1)

array([3], dtype=int64)

In [43]:
test=['Originally launched as the International Sun-Earth Explorer-3 in 1978, ICE was one of three spacecraft built for the International Sun-Earth Explorer (ISEE) program, a joint effort by NASA']
cleaned_data=[]

for i in test:
    t = clean(i)             #sci.space news https://www.space.com/39251-on-this-day-in-space.html
    cleaned_data.append(t)
t1=cvt.transform(cleaned_data)
log.predict(t1)

array([4], dtype=int64)

In [44]:
test1=['Gaming graphics card allows faster, more precise control of fusion energy experiments']
cleaned_data1=[]
for i in test1:
    t=clean(i)
    cleaned_data1.append(t)      # computer graphics news https://www.sciencedaily.com/releases/2021/07/210722131342.htm
t2=cvt.transform(cleaned_data1)
log.predict(t2)

array([0], dtype=int64)

# SVM & SVC

In [45]:
from sklearn.svm import SVC

In [46]:
clf=SVC(kernel='rbf',gamma=0.00193)

In [47]:
clf.fit(cv_train,Y)

SVC(gamma=0.00193)

In [48]:
clf.score(cv_test,ytest)

0.8917438921651222

In [49]:
clf.score(cv_train,Y)

0.9702914798206278

In [50]:
accuracy_score(ytest,clf.predict(cv_test))

0.8917438921651222